# Generated by Django 5.2.17 on 2026-09-29 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('text', models.CharField(blank=True, max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('link', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='clips/')),
                ('video_url', models.URLField(blank=True)),
                ('external_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('genre', models.CharField(choices=[('romance', 'Romance'), ('comedy', 'Comedy'), ('action', 'Action'), ('sci-fi', 'Sci-Fi'), ('suspense', 'Suspense'), ('thriller', 'Thriller'), ('adventure', 'Adventure'), ('faith-based', 'Faith Based')], max_length=30)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/')),
                ('trailer_url', models.URLField(blank=True)),
                ('external_link', models.URLField(blank=True)),
                ('is_most_recommended', models.BooleanField(default=False)),
                ('top_position', models.PositiveSmallIntegerField(blank=True, help_text='1-5 for Top 5', null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors/')),
                ('biography', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=120)),
                ('movies', models.ManyToManyField(blank=True, related_name='actors', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('nominees', models.ManyToManyField(blank=True, related_name='weekly_votes', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(max_length=128)),
                ('value', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='movies.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie', 'visitor_key'), name='one_movie_reaction_per_visitor')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyVoteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_entries', to='movies.movie')),
                ('weekly_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='movies.weeklyvote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('weekly_vote', 'visitor_key'), name='one_weekly_vote_per_visitor')],
            },
        ),
    ]
